"""
SQLAlchemy model for the TechAdmin operations table.

The operations table is an approved catalog of API, script, and
automation-job tools that the TechAdmin agent is allowed to select.

Important behavior:
1. operation_id is generated automatically by Python.
2. operation_code uniquely identifies an operation.
3. created_at is generated automatically in UTC.
4. script_name remains NULL for operations that do not use scripts.
5. is_active determines whether the agent may select the operation.
"""

import uuid
from datetime import datetime, timezone

from sqlalchemy import Boolean, DateTime, String
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from App.db.base import Base
from App.db.connection import DB_SCHEMA


def utc_now() -> datetime:
    """
    Return the current timezone-aware UTC timestamp.

    DateTime(timezone=True) maps this value to PostgreSQL
    TIMESTAMP WITH TIME ZONE.
    """

    return datetime.now(timezone.utc)


class Operation(Base):
    """
    Represents one approved TechAdmin operation.

    The table is explicitly assigned to DB_SCHEMA so that it is
    created as techadmin.operations instead of public.operations.
    """

    __tablename__ = "operations"

    __table_args__ = {
        "schema": DB_SCHEMA,
    }

    # Internal immutable primary key generated by Python when the
    # operation is first inserted.
    operation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        nullable=False,
    )

    # Stable machine-readable identifier used by the orchestrator,
    # router, policy layer, and other application components.
    #
    # Examples:
    # GET_USER_DETAILS
    # RESET_PASSWORD
    operation_code: Mapped[str] = mapped_column(
        String(100),
        unique=True,
        nullable=False,
        index=True,
    )

    # Friendly name used in logs, user interfaces, and reports.
    operation_name: Mapped[str] = mapped_column(
        String(200),
        nullable=False,
    )

    # Defines how the actual operation is executed.
    #
    # Supported values in the current design:
    # API, SCRIPT, JOB
    execution_type: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
    )

    # Name of the registered Python tool, wrapper, or callable
    # selected by the TechAdmin application.
    tool_name: Mapped[str] = mapped_column(
        String(150),
        nullable=False,
    )

    # Filename of the approved script when execution_type is SCRIPT.
    #
    # API and JOB operations can leave this column as NULL.
    script_name: Mapped[str | None] = mapped_column(
        String(255),
        nullable=True,
    )

    # Security classification of the operation.
    #
    # Accepted values:
    # LOW, MEDIUM, HIGH, CRITICAL
    risk_level: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
    )

    # True means the operation must pass through an approval
    # workflow before execution.
    requires_approval: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
    )

    # True means the operation is available for agent selection.
    # False disables selection without deleting the catalog record.
    is_active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
    )

    # UTC timestamp generated once when the operation is created.
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utc_now,
    )

    def __repr__(self) -> str:
        """
        Return a concise developer-friendly representation.

        This representation can safely be used during debugging
        because it does not contain authentication secrets.
        """

        return (
            "Operation("
            f"operation_id={self.operation_id}, "
            f"operation_code='{self.operation_code}', "
            f"execution_type='{self.execution_type}', "
            f"is_active={self.is_active}"
            ")"
        )