



[auth]

redirect_uri = "http://techadmin.coforge.com//oauth2callback"


cookie_secret = "43ae40da58d2fb23278fa6b0cb17e531044800b7f22d227e1567eaca7d6577a4"

client_id = "e7703fd5-d7f7-449e-af4c-cc3ea628aa23"

client_secret = "i_p8Q~C_HvHPLuSx6f2PU114-JeOEC.dkMz6CbEB"

server_metadata_url = "https://login.microsoftonline.com/b727a530-a0d5-4fb8-bd40-d8f9763e97db/v2.0/.well-known/openid-configuration"